project_id = "njyoimhjfqtygnlccjzq"

[functions.create-checkout-session]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.process-linkedin-pdf]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.send-support-email]
verify_jwt = false

[functions.sitemap]
verify_jwt = false
