export const ENGINE_LABELS: Record<string, string> = {
  unity: "Unity",
  unreal: "Unreal Engine",
  godot: "Godot",
  gamemaker: "GameMaker",
  construct: "Construct",
  rpg_maker: "RPG Maker",
  defold: "Defold",
  cocos: "Cocos",
  pygame: "Pygame",
  custom: "Engine Customizada",
  renpy: "Ren'Py",
  heaps: "Heaps.io",
  bevy: "Bevy",
  flax: "Flax Engine",
  cryengine: "CryEngine",
  source_2: "Source 2",
  gdevelop: "GDevelop",
  solar2d: "Solar2D",
  bitsy: "Bitsy",
  pico_8: "PICO-8",
  adventure_game_studio: "Adventure Game Studio",
  openfl: "OpenFL",
  monogame: "MonoGame",
  stride: "Stride",
  outro: "Outro",
};

export const PLATAFORMA_LABELS: Record<string, string> = {
  pc_windows: "Windows",
  pc_linux: "Linux",
  pc_macos: "macOS",
  mobile_android: "Android",
  mobile_ios: "iOS",
  console_playstation_4: "PlayStation 4",
  console_playstation_5: "PlayStation 5",
  console_xbox_one: "Xbox One",
  console_xbox_series: "Xbox Series",
  console_nintendo_switch: "Nintendo Switch",
  web_browser: "Navegador Web",
  vr_meta_quest: "Meta Quest",
  vr_steamvr: "SteamVR",
  vr_psvr: "PlayStation VR",
  ar_core: "ARCore (Android)",
  ar_kit: "ARKit (iOS)",
  arcade: "Arcade",
  cloud_gaming: "Cloud Gaming",
  handheld_retro: "Handheld Retrô",
  outro: "Outro",
};

export const GENERO_LABELS: Record<string, string> = {
  acao: "Ação",
  aventura: "Aventura",
  rpg: "RPG",
  estrategia: "Estratégia",
  simulacao: "Simulação",
  esportes: "Esportes",
  corrida: "Corrida",
  puzzle: "Puzzle",
  plataforma: "Plataforma",
  terror: "Terror",
  ficcao_cientifica: "Ficção Científica",
  casual: "Casual",
  idle: "Idle",
  tower_defense: "Tower Defense",
  battle_royale: "Battle Royale",
  mmo: "MMO",
  visual_novel: "Visual Novel",
  metroidvania: "Metroidvania",
  roguelike: "Roguelike",
  roguelite: "Roguelite",
  soulslike: "Soulslike",
  sandbox: "Sandbox",
  sobrevivencia: "Sobrevivência",
  musical: "Musical",
  luta: "Luta",
  tiro_fps: "Tiro (FPS)",
  tiro_tps: "Tiro (TPS)",
  card_game: "Card Game",
  party_game: "Party Game",
  educativo: "Educativo",
  hack_and_slash: "Hack and Slash",
  stealth: "Stealth",
  point_and_click: "Point and Click",
  walking_simulator: "Walking Simulator",
  bullet_hell: "Bullet Hell",
  shoot_em_up: "Shoot 'em Up",
  beat_em_up: "Beat 'em Up",
  jrpg: "JRPG",
  wrpg: "WRPG",
  tactical_rpg: "Tactical RPG",
  dungeon_crawler: "Dungeon Crawler",
  arpg: "ARPG",
  rts: "RTS",
  tbs: "TBS",
  grand_strategy: "Grand Strategy",
  "4x": "4X",
  auto_battler: "Auto Battler",
  tycoon: "Tycoon",
  life_sim: "Life Sim",
  farming_sim: "Farming Sim",
  god_game: "God Game",
  immersive_sim: "Immersive Sim",
  survivors_like: "Survivors-like",
  hidden_object: "Hidden Object",
  social_deduction: "Social Deduction",
  trivia: "Trivia",
  pinball: "Pinball",
  ritmo: "Ritmo",
  fmv: "FMV",
  terror_psicologico: "Terror Psicológico",
  survival_horror: "Survival Horror",
  moba: "MOBA",
  clicker: "Clicker",
  deckbuilder: "Deckbuilder",
  metajogo: "Metajogo",
  noir: "Noir",
  fantasia: "Fantasia",
  cyberpunk: "Cyberpunk",
  steampunk: "Steampunk",
  outro: "Outro",
};
