export const StatusProjeto = {
  EM_ANDAMENTO: 'em_andamento',
  CONCLUIDO: 'concluido',
  PAUSADO: 'pausado',
} as const;

export type StatusProjeto = typeof StatusProjeto[keyof typeof StatusProjeto];

export const EngineProjeto = {
  UNITY: 'unity',
  UNREAL: 'unreal',
  GODOT: 'godot',
  GAMEMAKER: 'gamemaker',
  CONSTRUCT: 'construct',
  RPG_MAKER: 'rpg_maker',
  DEFOLD: 'defold',
  COCOS: 'cocos',
  PYGAME: 'pygame',
  CUSTOM: 'custom',
  RENPY: 'renpy',
  HEAPS: 'heaps',
  BEVY: 'bevy',
  FLAX: 'flax',
  CRYENGINE: 'cryengine',
  SOURCE_2: 'source_2',
  GDEVELOP: 'gdevelop',
  SOLAR2D: 'solar2d',
  BITSY: 'bitsy',
  PICO_8: 'pico_8',
  ADVENTURE_GAME_STUDIO: 'adventure_game_studio',
  OPENFL: 'openfl',
  MONOGAME: 'monogame',
  STRIDE: 'stride',
  OUTRO: 'outro',
} as const;

export type EngineProjeto = typeof EngineProjeto[keyof typeof EngineProjeto];

export const PlataformaProjeto = {
  PC_WINDOWS: 'pc_windows',
  PC_LINUX: 'pc_linux',
  PC_MACOS: 'pc_macos',
  MOBILE_ANDROID: 'mobile_android',
  MOBILE_IOS: 'mobile_ios',
  CONSOLE_PLAYSTATION_4: 'console_playstation_4',
  CONSOLE_PLAYSTATION_5: 'console_playstation_5',
  CONSOLE_XBOX_ONE: 'console_xbox_one',
  CONSOLE_XBOX_SERIES: 'console_xbox_series',
  CONSOLE_NINTENDO_SWITCH: 'console_nintendo_switch',
  WEB_BROWSER: 'web_browser',
  VR_META_QUEST: 'vr_meta_quest',
  VR_STEAMVR: 'vr_steamvr',
  VR_PSVR: 'vr_psvr',
  AR_CORE: 'ar_core',
  AR_KIT: 'ar_kit',
  ARCADE: 'arcade',
  CLOUD_GAMING: 'cloud_gaming',
  HANDHELD_RETRO: 'handheld_retro',
  OUTRO: 'outro',
} as const;

export type PlataformaProjeto = typeof PlataformaProjeto[keyof typeof PlataformaProjeto];

export const GeneroProjeto = {
  ACAO: 'acao',
  AVENTURA: 'aventura',
  RPG: 'rpg',
  ESTRATEGIA: 'estrategia',
  SIMULACAO: 'simulacao',
  ESPORTES: 'esportes',
  CORRIDA: 'corrida',
  PUZZLE: 'puzzle',
  PLATAFORMA: 'plataforma',
  TERROR: 'terror',
  FICCAO_CIENTIFICA: 'ficcao_cientifica',
  CASUAL: 'casual',
  IDLE: 'idle',
  TOWER_DEFENSE: 'tower_defense',
  BATTLE_ROYALE: 'battle_royale',
  MMO: 'mmo',
  VISUAL_NOVEL: 'visual_novel',
  METROIDVANIA: 'metroidvania',
  ROGUELIKE: 'roguelike',
  ROGUELITE: 'roguelite',
  SOULSLIKE: 'soulslike',
  SANDBOX: 'sandbox',
  SOBREVIVENCIA: 'sobrevivencia',
  MUSICAL: 'musical',
  LUTA: 'luta',
  TIRO_FPS: 'tiro_fps',
  TIRO_TPS: 'tiro_tps',
  CARD_GAME: 'card_game',
  PARTY_GAME: 'party_game',
  EDUCATIVO: 'educativo',
  HACK_AND_SLASH: 'hack_and_slash',
  STEALTH: 'stealth',
  POINT_AND_CLICK: 'point_and_click',
  WALKING_SIMULATOR: 'walking_simulator',
  BULLET_HELL: 'bullet_hell',
  SHOOT_EM_UP: 'shoot_em_up',
  BEAT_EM_UP: 'beat_em_up',
  JRPG: 'jrpg',
  WRPG: 'wrpg',
  TACTICAL_RPG: 'tactical_rpg',
  DUNGEON_CRAWLER: 'dungeon_crawler',
  ARPG: 'arpg',
  RTS: 'rts',
  TBS: 'tbs',
  GRAND_STRATEGY: 'grand_strategy',
  QUATRO_X: '4x',
  AUTO_BATTLER: 'auto_battler',
  TYCOON: 'tycoon',
  LIFE_SIM: 'life_sim',
  FARMING_SIM: 'farming_sim',
  GOD_GAME: 'god_game',
  IMMERSIVE_SIM: 'immersive_sim',
  SURVIVORS_LIKE: 'survivors_like',
  HIDDEN_OBJECT: 'hidden_object',
  SOCIAL_DEDUCTION: 'social_deduction',
  TRIVIA: 'trivia',
  PINBALL: 'pinball',
  RITMO: 'ritmo',
  FMV: 'fmv',
  TERROR_PSICOLOGICO: 'terror_psicologico',
  SURVIVAL_HORROR: 'survival_horror',
  MOBA: 'moba',
  CLICKER: 'clicker',
  DECKBUILDER: 'deckbuilder',
  METAJOGO: 'metajogo',
  NOIR: 'noir',
  FANTASIA: 'fantasia',
  CYBERPUNK: 'cyberpunk',
  STEAMPUNK: 'steampunk',
  OUTRO: 'outro',
} as const;

export type GeneroProjeto = typeof GeneroProjeto[keyof typeof GeneroProjeto];
